### ISSUE TITLE
installation on windows 10 

### ISSUE THREAD

**Issue by AntonioEscamilla** [saulzar/multical#1]
The installation using pip fails on windows 10

The dependency "apriltags2-ethz" produce an error when using "pip install multical"

_(opencv4) PS C:\> pip install multical
Collecting multical
  Downloading multical-0.1.2.1.tar.gz (47 kB)
     |████████████████████████████████| 47 kB 378 kB/s
Requirement already satisfied: numpy in c:\virtualenvs\opencv4\lib\site-packages (from multical) (1.19.3)
Requirement already satisfied: scipy in c:\virtualenvs\opencv4\lib\site-packages (from multical) (1.4.1)
Requirement already satisfied: matplotlib in c:\virtualenvs\opencv4\lib\site-packages (from multical) (3.3.2)
Requirement already satisfied: opencv-python>=4.2.0.0 in c:\virtualenvs\opencv4\lib\site-packages (from multical) (4.4.0.44)
Requirement already satisfied: opencv-contrib-python in c:\virtualenvs\opencv4\lib\site-packages (from multical) (4.4.0.44)
Collecting natsort
  Downloading natsort-7.1.1-py3-none-any.whl (35 kB)
Collecting cached-property
  Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting py-structs>=0.2.1
  Downloading py-structs-0.2.3.tar.gz (6.4 kB)
ERROR: Could not find a version that satisfies the requirement apriltags2-ethz (from multical) (from versions: none)
ERROR: No matching distribution found for apriltags2-ethz (from multical)_

Is apriltags2-ethz package available only for Linux?

Is it possible to use multical without apriltags2-ethz?

**Comment by saulzar** [comment]
Yup. It’s only needed for Apriltag marker detection. Ill see if it’s
possible to make platform dependent.

**Comment by saulzar** [comment]
I have made the apriltags2-ethz package optional (will just complain if you try to use an aprilgrid configuration).

**Comment by AntonioEscamilla** [comment]
Thanks!!
I managed to install it this way
