### ISSUE TITLE
save board error

### ISSUE THREAD

**Issue by chaytonmin** [saulzar/multical#10]
multical    version:  0.2.0
command:   
multical boards --boards example_boards/charuco_16x22.yaml --paper_size A2 --pixels_mm 10 --write_images
usage: multical [-h] {calibrate,intrinsic,boards,vis} ...
multical: error: unrecognized arguments: --write_images

**Comment by saulzar** [comment]
Hi,

I have updated the README, it should be just '--write', thanks!
