### ISSUE TITLE
Can multical be used for multi cameras both intrinsic and extrinsic calibration together?

### ISSUE THREAD

**Issue by chaytonmin** [saulzar/multical#3]
Can multical be used for multi cameras both intrinsic and extrinsic calibration together?

**Comment by saulzar** [comment]
Yes.

**Comment by chaytonmin** [comment]
![Screenshot from 2021-05-04 09-28-11](https://user-images.githubusercontent.com/40260488/117011811-3c464780-acbc-11eb-97be-3cad9b9d6782.png)

I met the error as above. However, I have installed the packege of apriltags2-ethz.

![Screenshot from 2021-05-04 09-37-58](https://user-images.githubusercontent.com/40260488/117011967-6c8de600-acbc-11eb-8cdb-b0724ab9eb28.png)

**Comment by chaytonmin** [comment]
> ![Screenshot from 2021-05-04 09-28-11](https://user-images.githubusercontent.com/40260488/117011811-3c464780-acbc-11eb-97be-3cad9b9d6782.png)
> 
> I met the error as above. However, I have installed the packege of apriltags2-ethz.
> 
> ![Screenshot from 2021-05-04 09-37-58](https://user-images.githubusercontent.com/40260488/117011967-6c8de600-acbc-11eb-8cdb-b0724ab9eb28.png)

The problem was caused by that multical uses another python.

**Comment by chaytonmin** [comment]
Can you provide the pdf format of Calibration Target for example_boards?  Thanks!

**Comment by saulzar** [comment]
Ah - thanks for checking.

Here's my workflow for making board images:

```
multical show_boards example_boards/charuco_16x22.yaml --paper_size A2 --pixels_mm 10 --write images
Using boards:
charuco_16x22 CharucoBoard {type='charuco', aruco_dict='4X4_1000', aruco_offset=0, size=(16, 22), marker_length=0.01875, square_length=0.025, aruco_params={}}
Wrote images/charuco_16x22.png
```

Then open up  images/charuco_16x22.png in gimp and print-to-file with the margins set to zero and the paper size set to A2. The 9x9 Aprilgrid board can work the same way, except that it's square so does not have a standard paper size - I think ours is 800x800mm, so you can make an image for it e.g.

**Comment by chaytonmin** [comment]
> Ah - thanks for checking.
> 
> Here's my workflow for making board images:
> 
> ```
> multical show_boards example_boards/charuco_16x22.yaml --paper_size A2 --pixels_mm 10 --write images
> Using boards:
> charuco_16x22 CharucoBoard {type='charuco', aruco_dict='4X4_1000', aruco_offset=0, size=(16, 22), marker_length=0.01875, square_length=0.025, aruco_params={}}
> Wrote images/charuco_16x22.png
> ```
> 
> Then open up images/charuco_16x22.png in gimp and print-to-file with the margins set to zero and the paper size set to A2. The 9x9 Aprilgrid board can work the same way, except that it's square so does not have a standard paper size - I think ours is 800x800mm, so you can make an image for it e.g.
> 
> `multical show_boards example_boards/aprilgrid_9x9.yaml --paper_size_mm 800x800 --pixels_mm 10 --write images`
> 
> But I'm not entirely sure how to convert that to a square pdf. I think we just sent it to the print shop as a png image to get that one printed.

Thanks a lot! I will try it.
